language: generic
deploy:
  provider: s3
  access_key_id: AKIAIHN5MLKGXPJR7H4Q
  secret_access_key:
    secure: "yf2Ukct0VPc7ABDWqvXcAMNSvcAGOdToNZZGt4uYCzkBVMUc864NZR2EQEmQa/b9DnlHbvsVRPwtX3iE4ZAjlh82OFoNQ13tEmYsjXlcGFxU65K0s/n6URmyLxuthaOZWN7BEmLqTRfN1ktXoh7YmjZG8yD1uHxjKOQIeECf9cVr0jAFieJv79hhFb/TZIg8zNPoxq7G35ANCHj9t3cJ3c5jGyp73f0XztyjVv6w7A1QkrHqLpuR+AM3PUD4B+5Fw+mWaK/XM6SHqOwR732695a6+SBS+AWX5sR21CAH8mtqQ/eG8mMDYA2ABcn9fGtTuu3nnkNjxrpFHHr1nXwxqwqSVyXYaB7TtuWWwOqr2ZHjJB3gL35O+HM8TZjXmAwySGiFSFdDDK7X1jLeJ6TGmEKBqYbi3GiM32o8mrd0AD9eDxX8ipCS38TV3KQYa3hcqVaw3D2e4WTEnb104uUygMTINz7ryCS+mE8G7AOtbZCZogYMTkGQlVKU7Ks6u5jmvdi7oQMhoaJPwwPEXojozRQY67dUmzXKLQScH04uNdvIHPVTSEx/LSEQLseYIeREjldqNZ+iTDFHWqqKrg5lv7qEo+PrQU2ke45EV3cSqjQyLHsv8v/Jdu1nLCvSfD4M8guVZi9eUowgmnILRPcQGcHBaU/mREiCYM6DAIAtEzY="
  bucket: elasticbeanstalk-us-west-2-893554244568
  skip_cleanup: true
  region: us-west-2
  acl: public_read  
  local-dir: public