
# html lang
language: en

# main menu navigation
menu:
  Home: /
  Case Studies: /archives
  About: /
  Urban Systems Lab: http://urbansystemslab.com/

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/kube.min.css
- /css/custom.css
- /css/prism-hopscotch.css

# scripts loaded in the end of the body
scripts:
- /js/jquery.min.js
- /js/kube.js
- /js/prism.js

node_sass:
  outputStyle: nested
  precision: 4
  sourceComments: false